//políticas de privacidades
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'media-src': ["'self'",
		  'data:',
		  'blob:',
		  "io.cnpgc.embrapa.br",
		  "https://tecnofamapp.cpao.embrapa.br",
		  "https://tecnofam-api.cpao.embrapa.br",
		  "https://tecnofam-strapi.cpao.embrapa.br",
		  "http://io.cnpgc.embrapa.br:49168",
		  "https://io.cnpgc.embrapa.br:49168",
		  "https://market-assets.strapi.io",
		  "https://tecnofam-strapi.a.cnpgc.embrapa.br",
		  "tecnofam-strapi.a.cnpgc.embrapa.br",
		  "tecnofam-minioapi.a.cnpgc.embrapa.br"],
            "frame-src": [
            "'self'",
            "youtube.com",
            "www.youtube.com",
            "vimeo.com",
            "*.vimeo.com",
            "facebook.com",
            "www.facebook.com",
          ],
          "connect-src": ["'self'", "https:", "blob:", "*.strapi.io", 'data:'],
          "img-src": [ "'self'",
		  "data:",
		  "blob:",
		  "dl.airtable.com",
		  "io.cnpgc.embrapa.br",
		  "https://tecnofamapp.cpao.embrapa.br",
		  "https://tecnofam-api.cpao.embrapa.br",
		  "https://tecnofam-strapi.cpao.embrapa.br",
		  "http://io.cnpgc.embrapa.br:49168",
		  "https://io.cnpgc.embrapa.br:49168",
		  "https://market-assets.strapi.io",
		  "https://tecnofam-strapi.a.cnpgc.embrapa.br",
		  "tecnofam-minioapi.a.cnpgc.embrapa.br",
		  "tecnofam-strapi.a.cnpgc.embrapa.br", ],
	  "style-src": ["'self'", "'unsafe-inline'"],
          "script-src": [
            "'self'",
            "cdn.jsdelivr.net",
            "blob:",
            "https:",
          ],
          "font-src": ["'self'"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  // {
  //  name: "strapi::cors",
  //  config: {
	//    origin: ["https://tecnofam-strapi.a.cnpgc.embrapa.br","tecnofam-strapi.a.cnpgc.embrapa.br","tecnofam-minioapi.a.cnpgc.embrapa.br", "io.cnpgc.embrapa.br", "io.cnpgc.embrapa.br:49168","http://io.cnpgc.embrapa.br", "http://io.cnpgc.embrapa.br:49168","http://localhost:1337", "https://tecnofam-strapi.cpao.embrapa.br","https://minio:9000","http://minio:9000/","minio","https://tecnofamapp.cpao.embrapa.br"],
  //       methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
  //       headers: ['Content-Type', 'Authorization', 'Origin', 'Accept'],
  //       keepHeaderOnError: true,
  //   },
  // },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  // { resolve: "./src/middlewares/redirect" },

];
